### ISSUE TITLE
2023/02/08の会

### ISSUE THREAD

**Issue by tabunmuri** [rta-hackathon/rta-hackathon-hq#3]
## 概要
- アナウンス
  - 参加される場合は、コンパスへの申込みお願いします 🙏 
- 会についての紹介
- 自己紹介
- 今週のハッカソン紹介
  - アップデートはとくになし

### 自己紹介
（これをコピペして、この後各自postしていきましょう〜）

```
## （名前）
- 得意なこと 
- 苦手なこと
- ちょっとした話
- 今日やること
- 助けが欲しいこと
```

### 今週のハッカソン紹介
- （あれば…）

**Comment by tabunmuri** [comment]
## tabunmuri
- 得意なこと
  - infra
    - aws, terraform, CICDセッティング
  - backend
    - ruby & Ruby and rails
    - php
    - nodejs
  - frontend
    - html & css
- 苦手なこと
  - エクセル作業や事務仕事
- ちょっとした話
  - 最近ダイエットしてます
- 助けが欲しいこと
  - 会の運営

### 今日やること
- [x] issue整理
  - infra
  - backend
  - frontend
- [x] issueテンプレートのアップデート
- [ ] 前回の続き
- [x] 来週の会の準備

**Comment by MM20000503** [comment]
## mamu_soba
- 得意なこと
  * OSやCPUなどの低レイヤ領域
  * C言語、アセンブリ、Python
  * 電子回路は少しわかる
- 苦手なこと
  * Web技術・インフラ
- ちょっとした話
  * 2021年のSecHack365に参加してました
- 今日やること
  * ハッカソン調べ、いろいろと勉強
- 助けが欲しいこと
  * Web技術とインフラ教えてください！！！(>人<)
- ハッカソン資料
https://www.slideshare.net/htus-ltd/ss-172871046
https://awrd.com/blog/2019/5/hac-tips

**Comment by yuni-shinogami** [comment]
慕狼ゆに
---
- 得意なこと
  - Web
    - React x Typescript
      - nodejs
    - Ruby, Ruby on Rails
    - Python
- 苦手なこと
  - 低レイヤー、インフラ 
- ちょっとした話
  - VRChatでエンジニア向けイベントをやっている
- 今日やること
  - 基本情報の勉強をする
  - 副業の開発作業をする
- 助けが欲しいこと
  - 何かアプリ作りをしたいけど、最近やること抱えて時間作れないな・・・という悩みを抱えている

**Comment by tabunmuri** [comment]
@MM20000503 
## インフラ
- サーバー選定
  - VPS(virtual private server)
    - https://vps.sakura.ad.jp/
  - AWS, GCP, Azure
- VPSにはIPが振られるんですよね。
  - IPドメインとIPの紐付けをすると
- ウェブサーバー
  - nginx or apache

## バックエンド
- フレームワーク
  - ruby on rails()
    - https://rubyonrails.org/
  - Laravel
- DB
  - PostgreSQL
  - MySQL
  - Redis
  - などなど

### Ruby on Rails
Ruby on Railsのつくり
- Model(DBからどんなデータの引き方をするか)
- Controller（このURLにアクセスされたときに、どういう条件のときにはどういうページを出すか？のコントロール）
   - aaaa.com/user/1 にアクセスしてきた場合に、ログインされていたらユーザの個別ページ、未識別ユーザーならトップページにリダイレクトするみたいな制御をする
- View（HTMLみたいにあたるところ）
  - HTMLに当たる部分
  - 組み込み変数が使えるので、必要に応じでDBからデータを引いてきて、その数値を反映したHTMLを出力させる

## 学習するなら…
- https://bootcamp.fjord.jp/practices
- https://dotinstall.com/lessons/basic_rails_v3
- https://www.sejuku.net/blog/39936

**Comment by tabunmuri** [comment]
## ハッカソン運営の資料
- https://www.slideshare.net/htus-ltd/ss-172871046
- https://awrd.com/blog/2019/5/hac-tips

**Comment by tabunmuri** [comment]
面白かった話
https://vrceve.com/
